Fix build with gcc-10
:Release Notes:
Fixes:
http://gecko.lge.com/Errors/Details/384977

:Detailed Notes:
qemux86_64-webos-linux/com.webos.service.memorymanager/1.0.0-52-r6/git/src/common/util/Cgroup.cpp: In static member function 'static void Cgroup::iterateDir(std::map<std::__cxx11::basic_string<char>, std::__cxx11::list<int> >&, std::string)':
qemux86_64-webos-linux/com.webos.service.memorymanager/1.0.0-52-r6/git/src/common/util/Cgroup.cpp:49:18: error: variable 'std::ifstream ifs' has initializer but incomplete type
   49 |     ifstream ifs(procs.c_str());
      |                  ^~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-10791] CCC: Various build fixes

Change-Id: Ia254ca5a9bb40b345e148acb49a611a9a43b1b33